import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nova To Cart",
  description: "Generated by Nova Cart Pakistan",
  keywords: ["Nova Cart", "E-commerce", "Online Shopping", "Pakistan", "Top E-commerce", "Best Online Store"],
  openGraph: {
    title: "Nova To Cart",
    description: "Generated by Nova Cart Pakistan",
    url: "https://novacart.info",
    siteName: "Nova To Cart",
    images: [
      {
        url: "https://novacart.info/thd1.jpg",
        width: 800,
        height: 600,
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Nova To Cart",
    description: "Generated by Nova Cart Pakistan",
    images: ["https://www.novacart.pk/logo.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link rel="icon" href="/thd1.jpg" />
          <meta name="keywords" content="Nova Cart, E-commerce, Online Shopping, Pakistan, Top E-commerce, Best Online Store" />
          <meta name="author" content="Nova Cart Pakistan" />
          <meta name="robots" content="index, follow" />
          <meta name="revisit-after" content="7 days" />
          <meta name="language" content="English" />
          <meta name="distribution" content="global" />
          <meta name="rating" content="general" />
          <meta name="googlebot" content="index, follow" />
          <meta name="bingbot" content="index, follow" />
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}